[tool.scikit-build]
cmake.minimum-version = "3.26.4"
ninja.make-fallback = true
build-dir = "build/{wheel_tag}"

[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "nvjitlink"
version = "0.1.0"
