package:
  name: nvjitlink
  version: 0.1.0

source:
  #url: https://github.com/rapidsai/nvjitlink/archive/refs/tags/0.1.0.tar.gz
  path: ../../

build:
  noarch: python
  script: pip install .

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda-nvcc') }}
    - cmake >=3.26.4
  host:
    - cuda-version=12.0
    - python
    - scikit-build
    - libnvjitlink-dev
    - libnvjitlink-static
    - cuda-nvcc-impl
  run:
    - python
    - numba >=0.57

test:
  imports:
    - nvjitlink
  source_files:
    - nvjitlink/tests/test_nvjitlink_api.py
    - nvjitlink/tests/test_nvjitlink.py
    - nvjitlink/tests/test_device_functions.cubin
    - nvjitlink/tests/test_device_functions.fatbin
    - nvjitlink/tests/undefined_extern.cubin
    

  requires:
    - pytest
  commands: 
    - pytest -v

about:
  home: https://github.com/rapidsai/nvjitlink
