# Copyright (c) 2023, NVIDIA CORPORATION.
name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - build-and-test-wheels
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.02
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@branch-24.02
    with:
      enable_check_generated_files: false
  build-and-test-wheels:
    uses: ./.github/workflows/build_and_test_wheels.yaml
  wheel-publish-pynvjitlink:
    needs:
      - build-and-test-wheels
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-publish.yaml@branch-24.02
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}
      package-name: pynvjitlink-cu12
