# Copyright (c) 2023, NVIDIA CORPORATION.
name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - build-and-test-wheels
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.02
  build-and-test-wheels:
    uses: ./.github/workflows/build_and_test_wheels.yaml
