# Copyright (c) 2023, NVIDIA CORPORATION.
on:
  workflow_call:

jobs:
  build-and-test-wheels:
    needs:
      - wheel-build-amd64
      - wheel-build-arm64
      - wheel-test-amd64
      - wheel-test-arm64
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.02
  wheel-build-amd64:
    runs-on: linux-amd64-cpu4
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    container:
      image: "rapidsai/ci-wheel:cuda12.0.1-centos7-py${{ matrix.python-version }}"
    steps:
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
        role-duration-seconds: 43200 # 12h
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Standardize repository information
      uses: rapidsai/shared-actions/rapids-github-info@main
      with:
        repo: ${{ inputs.repo }}
        branch: ${{ inputs.branch }}
        date: ${{ inputs.date }}
        sha: ${{ inputs.sha }}
    - name: Run build_wheel.sh
      run: ci/build_wheel.sh
  wheel-build-arm64:
    runs-on: linux-arm64-cpu4
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    container:
      image: "rapidsai/ci-wheel:cuda12.0.1-rockylinux8-py${{ matrix.python-version }}"
    steps:
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ vars.AWS_ROLE_ARN }}
        aws-region: ${{ vars.AWS_REGION }}
        role-duration-seconds: 43200 # 12h
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Standardize repository information
      uses: rapidsai/shared-actions/rapids-github-info@main
      with:
        repo: ${{ inputs.repo }}
        branch: ${{ inputs.branch }}
        date: ${{ inputs.date }}
        sha: ${{ inputs.sha }}
    - name: Run build_wheel.sh
      run: ci/build_wheel.sh
  wheel-test-amd64:
    needs:
      - wheel-build-amd64
    runs-on: linux-amd64-gpu-v100-latest-1
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        linux-version: ["ubuntu20.04", "ubuntu18.04"]
    container:
      image: "rapidsai/citestwheel:cuda12.0.1-${{ matrix.linux-version }}-py${{ matrix.python-version }}"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run test_wheel.sh
      run: ci/test_wheel.sh
  wheel-test-arm64:
    needs:
      - wheel-build-arm64
    runs-on: linux-arm64-gpu-a100-latest-1
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    container:
      image: "rapidsai/citestwheel:cuda12.0.1-ubuntu20.04-py${{ matrix.python-version }}"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run test_wheel.sh
      run: ci/test_wheel.sh
