# Copyright (c) 2023, NVIDIA CORPORATION.
name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - wheel-build
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@branch-23.12
  checks:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/checks.yaml@branch-23.12
    with:
      enable_check_generated_files: false
  wheel-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    container:
      # Use CentOS 7 for an old glibc version, so the wheel has broad manylinux compatibility.
      image: "rapidsai/ci-conda:cuda12.0.1-centos7-py3.10"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get PR Info
      id: get-pr-info
      uses: rapidsai/shared-actions/get-pr-info@main
    - name: Run build_wheel.sh
      run: ci/build_wheel.sh ${{ matrix.python-version }}
    - name: Upload Python Wheel
      uses: actions/upload-artifact@v2
      with:
        name: pynvjitlink-*.whl
        path: ./
  wheel-test:
    needs:
      - wheel-build
    runs-on: ubuntu-latest
    container:
      image: "rapidsai/ci-conda:cuda12.0.1-centos7-py3.10"
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get PR Info
      id: get-pr-info
      uses: rapidsai/shared-actions/get-pr-info@main
    - name: Download Python Wheel
      uses: actions/download-artifact@v2
      with:
        name: pynvjitlink*.whl
        path: ./
    - name: run test_wheel.sh
      run: ci/test_wheel.sh ${{ matrix.python-version }}
