# Copyright (c) 2023, NVIDIA CORPORATION.
name: Build and test

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - compute-matrix-build
      - compute-matrix-test
      - build-wheels
      - test-wheels
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.02
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@branch-24.02
    with:
      enable_check_generated_files: false
      enable_check_pr_job_dependencies: false
  compute-matrix-build:
    uses: ./.github/workflows/build_matrix.yml
  compute-matrix-test:
    uses: ./.github/workflows/test_matrix.yml
  build-wheels:
    needs:
      - compute-matrix-build
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.02
    with:
      build_type: pull-request
      script: "ci/build_wheel.sh"
      matrix_filter: ${{ needs.compute-matrix-build.outputs.MATRIX }}
  test-wheels:
    needs:
      - build-wheels
      - compute-matrix-test
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.02
    with:
      build_type: pull-request
      script: "ci/test_wheel.sh"
      matrix_filter: ${{ needs.compute-matrix-test.outputs.MATRIX }}
