# Copyright (c) 2023, NVIDIA CORPORATION.
name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - checks
      - wheel-build
      - wheel-test-amd64
      - wheel-test-arm64
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/pr-builder.yaml@branch-23.12
  checks:
    secrets: inherit
    uses: rapidsai/shared-action-workflows/.github/workflows/checks.yaml@branch-23.12
    with:
      enable_check_generated_files: false
  wheel-build:
    runs-on: linux-${{ matrix.arch }}-cpu4
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        arch: ["arm64", "amd64"]
    container:
      # Use CentOS 7 for an old glibc version, so the wheel has broad manylinux compatibility.
      image: "rapidsai/ci-wheel:cuda12.0.1-rockylinux8-py${{ matrix.python-version }}"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get PR Info
      id: get-pr-info
      uses: rapidsai/shared-actions/get-pr-info@main
    - name: Run build_wheel.sh
      run: ci/build_wheel.sh
    - name: Upload Python Wheel
      uses: actions/upload-artifact@v2
      with:
        path: ./wheel-build
  wheel-test-amd64:
    needs:
      - wheel-build
    runs-on: linux-amd64-gpu-v100-latest-1
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        linux-version: ["centos7", "rockylinux8"]
    container:
      image: "rapidsai/citestwheel:cuda12.0.1-ubuntu20.04-py${{ matrix.python-version }}"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get PR Info
      id: get-pr-info
      uses: rapidsai/shared-actions/get-pr-info@main
    - name: Download Python Wheel
      uses: actions/download-artifact@v2
      with:
        path: ./
    - name: Run test_wheel.sh
      run: ci/test_wheel.sh 
  wheel-test-arm64:
    needs:
      - wheel-build
    runs-on: linux-arm64-gpu-a100-latest-1
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        linux-version: ["centos7", "rockylinux8"]
    container:
      image: "rapidsai/citestwheel:cuda12.0.1-ubuntu20.04-py${{ matrix.python-version }}"
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get PR Info
      id: get-pr-info
      uses: rapidsai/shared-actions/get-pr-info@main
    - name: Download Python Wheel
      uses: actions/download-artifact@v2
      with:
        path: ./
    - name: run test_wheel.sh
      run: ci/test_wheel.sh 
