# Copyright (c) 2023, NVIDIA CORPORATION.

on:
  workflow_call:

jobs:
  compute-matrix-test:
    runs-on: ubuntu-latest
    outputs:
      MATRIX: ${{ steps.compute-matrix-test.outputs.MATRIX }}
    steps:
      - name: Compute Build Matrix
        id: compute-matrix-test
        run: |
          set -eo pipefail

          export MATRIX="
          - { CUDA_VER: '12.0.1', ARCH: 'amd64', PY_VER: '3.9', LINUX_VER: 'ubuntu18.04', gpu: 'v100', driver: 'latest' }
          - { CUDA_VER: '12.0.1', ARCH: 'amd64', PY_VER: '3.10', LINUX_VER: 'ubuntu18.04', gpu: 'v100', driver: 'latest' }
          - { CUDA_VER: '12.0.1', ARCH: 'arm64', PY_VER: '3.9', LINUX_VER: 'ubuntu20.04', gpu: 'a100', driver: 'latest' }
          - { CUDA_VER: '12.0.1', ARCH: 'arm64', PY_VER: '3.10', LINUX_VER: 'ubuntu20.04', gpu: 'a100', driver: 'latest' }
          "

          echo "MATRIX=$(
            yq -n -o json 'env(MATRIX)' | \
            jq -c '.' \
          )" | tee --append "${GITHUB_OUTPUT}"
